services:
  scoresmaster-api-football:
    build:
      context: ./ScoresMasterApi_Football
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=scoresmaster;Username=postgres;Password=postgres

  scoresmaster-frontend:
    build:
      context: ./scoresmaster-frontend
    ports:
      - "3000:80"
    depends_on:
      - scoresmaster-api-football

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: scoresmaster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
